"""Jay3 migration

Revision ID: 5d18fcb7ee37
Revises: 67da18e77971
Create Date: 2024-07-08 18:35:12.807122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d18fcb7ee37'
down_revision: Union[str, None] = '67da18e77971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() :
    # ### commands auto generated by Alembic - please adjust! ###
        # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###
    pass
    # ### end Alembic commands ###


def downgrade() :
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.add_column('profiles', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    pass
    # ### end Alembic commands ###
